### ISSUE TITLE
只能全局引入？

### ISSUE THREAD

**Issue by airzhanglin** [wisewrong/vue-tag-textarea#4]
import VueTagTextarea from 'vue-tag-textarea'
import 'vue-tag-textarea/lib/vue-tag-textarea.css'
export default {
  name: 'app',
  components: {
    wechatPlayer,
    VueTagTextarea
  }
}
</script>这种方式有问题  报错   Failed to mount component: template or render function not defined.

**Comment by wisewrong** [comment]
全局引入应该是没有问题的，检查一下代码吧。
如果想作为一个组件引入，可以把 /packages/textarea 目录单独拷出来，放到自己的项目中 💪
